src/MvcZoolandia/Models/Animal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MvcZoolandia.Models
{
    public class Animal
    {
        public int ID { get; set; }

        [RegularExpression(@"^[A-Z]+[a-zA-Z''-'\s]*$"), Required, StringLength(30)]
        public string Name { get; set; }
        [Required]
        public int IdHabitat { get; set; }
        [Required]
        public int IdSpecies { get; set; }
    }
}

src/MvcZoolandia/ViewModels/AnimalViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MvcZoolandia.ViewModels
{
    public class AnimalViewModel
    {
        public int ID { get; set; }
        public string Animal { get; set; }
        public string Habitat { get; set; }
        public string Species { get; set; }
    }
}

src/MvcZoolandia/Controllers/AnimalController.cs
using System.Linq;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using MvcZoolandia.Models;
using System.Collections;
using MvcZoolandia.ViewModels;
using System;

namespace MvcZoolandia.Controllers
{
    public class AnimalController : Controller
    {
        private ApplicationDbContext _context;

        public AnimalController(ApplicationDbContext context)
        {
            _context = context;    
        }

        // GET: Animals
        public IActionResult Index(string searchString)
        {
            var  ListOfAnimals =
                (from animal in _context.Animal
                 join habitat in _context.Habitat
                 on animal.IdHabitat equals habitat.ID

                 join species in _context.Species
                 on animal.IdSpecies equals species.ID

                 
                 //basically means 'create new' based on search results
                 select new AnimalViewModel
                 {
                     ID = animal.ID,
                     Animal = animal.Name,
                     Habitat = habitat.Name,
                     Species = species.commonName

                 }).ToList();

            if (!String.IsNullOrEmpty(searchString))
            {
                var filteredAnimalInfo = ListOfAnimals.Where(item => item.Animal == searchString);
                return View(filteredAnimalInfo);
            }

            return View(ListOfAnimals);
        }

        // GET: Animals/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Animal animal = _context.Animal.Single(m => m.ID == id);
            if (animal == null)
            {
                return HttpNotFound();
            }

            return View(animal);
        }

        // GET: Animals/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Animals/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Animal animal)
        {
            if (ModelState.IsValid)
            {
                _context.Animal.Add(animal);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(animal);
        }

        // GET: Animals/Edit/5
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Animal animal = _context.Animal.Single(m => m.ID == id);
            if (animal == null)
            {
                return HttpNotFound();
            }
            return View(animal);
        }

        // POST: Animals/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit([Bind("ID,Animal,Habitat,Species")] Animal animal)
        {
            if (ModelState.IsValid)
            {
                _context.Update(animal);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(animal);
        }

        // GET: Animals/Delete/5
        [ActionName("Delete")]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return HttpNotFound();
            }

            Animal animal = _context.Animal.Single(m => m.ID == id);
            if (animal == null)
            {
                return HttpNotFound();
            }

            return View(animal);
        }

        // POST: Animals/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Animal animal = _context.Animal.Single(m => m.ID == id);
            _context.Animal.Remove(animal);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

src/MvcZoolandia/Views/Animal/Create.cshtml
@model MvcZoolandia.Models.Animal

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Animal</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="IdHabitat" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IdHabitat" class="form-control" />
                <span asp-validation-for="IdHabitat" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IdSpecies" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IdSpecies" class="form-control" />
                <span asp-validation-for="IdSpecies" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/MvcZoolandia/Views/Animal/Delete.cshtml
@model MvcZoolandia.Models.Animal

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Animal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdHabitat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdHabitat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdSpecies)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdSpecies)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/MvcZoolandia/Views/Animal/Details.cshtml
@model MvcZoolandia.Models.Animal

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Animal</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IdHabitat)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdHabitat)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IdSpecies)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IdSpecies)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
    </dl>
</div>
<p>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</p>

src/MvcZoolandia/Views/Animal/Edit.cshtml
@model MvcZoolandia.Models.Animal

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Animal</h4>
        <hr />
        <div asp-validation-summary="ValidationSummary.ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label asp-for="IdHabitat" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IdHabitat" class="form-control" />
                <span asp-validation-for="IdHabitat" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="IdSpecies" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="IdSpecies" class="form-control" />
                <span asp-validation-for="IdSpecies" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="Name" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

src/MvcZoolandia/Views/Animal/Index.cshtml
@model IEnumerable<MvcZoolandia.ViewModels.AnimalViewModel>

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Animal" asp-action="Index" method="post">
    <p>
        Title: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Habitat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Species)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Animal)
        </th>
        <th></th>
    </tr>
    
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Habitat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Species)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Animal)
        </td>
        <td>
            <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
        </td>
    </tr>
}
</table>